version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - DB:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  DB:
